// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Button(Props) {
  var name = Props.name;
  return React.createElement("button", {
              style: {
                color: "#444444",
                fontSize: "16px",
                marginTop: "20px"
              }
            }, name);
}

var make = Button;

exports.make = make;
/* react Not a pure module */
