// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Header(Props) {
  var name = Props.name;
  return React.createElement("div", {
              style: {
                color: "#444444",
                fontFamily: "sans-serif",
                fontSize: "40px",
                paddingTop: "40px"
              }
            }, "" + name);
}

var make = Header;

exports.make = make;
/* react Not a pure module */
