// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var Input$ReactHooksTemplate = require("./Input.bs.js");
var Header$ReactHooksTemplate = require("./Header.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement(Header$ReactHooksTemplate.make, {
          name: "Header"
        }), "index1");

ReactDOMRe.renderToElementWithId(React.createElement(Input$ReactHooksTemplate.make, { }), "input");

/*  Not a pure module */
