// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");

function Input(Props) {
  var match = React.useState((function () {
          return "";
        }));
  var setText = match[1];
  var text = match[0];
  var handler = function ($$event) {
    return Curry._1(setText, $$event.target.value);
  };
  console.log(text);
  return React.createElement(React.Fragment, undefined, React.createElement("input", {
                  style: {
                    paddingTop: "4px",
                    paddingBottom: "4px"
                  },
                  placeholder: "Placeholder",
                  value: text,
                  onChange: handler
                }), React.createElement("button", undefined, "Button"));
}

var make = Input;

exports.make = make;
/* react Not a pure module */
